### ISSUE TITLE
evkmimx8mm: missing pinmux call

### ISSUE THREAD

**Issue by dariis** [nxp-mcuxpresso/mcux-sdk-examples#10]
The examples do not work without adding the line `BOARD_InitPins();` to `BOARD_InitBootPins()`

https://github.com/NXPmicro/mcux-sdk-examples/blob/a32cda929f3e77b4aa55d104b000c2e74da7f49a/evkmimx8mm/driver_examples/ecspi/interrupt_b2b_transfer/master/pin_mux.c#L36-L38

```c
void BOARD_InitBootPins(void) 
 { 
    BOARD_InitPins();
 } 
```

https://github.com/NXPmicro/mcux-sdk-examples/blob/a32cda929f3e77b4aa55d104b000c2e74da7f49a/evkmimx8mm/driver_examples/ecspi/interrupt_b2b_transfer/slave/pin_mux.c#L36-L38

```c
void BOARD_InitBootPins(void) 
 { 
    BOARD_InitPins();
 } 
```

https://github.com/NXPmicro/mcux-sdk-examples/blob/a32cda929f3e77b4aa55d104b000c2e74da7f49a/evkmimx8mm/driver_examples/ecspi/polling_b2b_transfer/master/pin_mux.c#L36-L38

```c
void BOARD_InitBootPins(void) 
 { 
    BOARD_InitPins();
 } 
```

https://github.com/NXPmicro/mcux-sdk-examples/blob/a32cda929f3e77b4aa55d104b000c2e74da7f49a/evkmimx8mm/driver_examples/ecspi/polling_b2b_transfer/slave/pin_mux.c#L36-L38

```c
void BOARD_InitBootPins(void) 
 { 
    BOARD_InitPins();
 } 
```

**Comment by mcuxsusan** [comment]
Thanks for reporting the issue. It would be great if you could help open a PR to contribute your fix back to us.

**Comment by dariis** [comment]
I could but isn't that a code generator problem?

 `- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: cm4}` compared to `- options: {callFromInitBoot: 'false', coreID: cm4}`

**Comment by mcuxsusan** [comment]
@dariis, yes, you are correct, the pin_mux file is generated by config tool. If you are familiar with our config tool, you could import the pin_mux file into our tool and generate an update one by using the correct option.

**Comment by dariis** [comment]
I am not familiar with the config tool but will still do a PR.
