### ISSUE TITLE
FreeRTOS timer settings not correct

### ISSUE THREAD

**Issue by carlocaione** [nxp-mcuxpresso/mcux-sdk-examples#28]
I'm using the `RT685 EVK` in a standard configuration.

The easiest way to reproduce the problem is by using the `freertos_swtimer` example.

Since we set `SW_TIMER_PERIOD_MS` to `(1000 / portTICK_PERIOD_MS)` we expect the timer to go off every second. In reality it goes off every ~500ms.

**Comment by MichalPrincNXP** [comment]
Hello @carlocaione , I am afraid I am not able to reproduce the issue. What SDK version, IDE and target are you using?
Regards
Michal

**Comment by carlocaione** [comment]
Yup, PEBKAC. Closing thanks.
