### ISSUE TITLE
Multicore armgcc examples "cannot" be built.

### ISSUE THREAD

**Issue by Hadatko** [nxp-mcuxpresso/mcux-sdk-examples#5]
Hello, i took complete sdk for rt1176 from [mcuxpresso.nxp.com](https://mcuxpresso.nxp.com/en/dashboard) see:
![image](https://user-images.githubusercontent.com/13130700/126305729-3f99d195-6947-4153-b098-9e3bfb6059c4.png)

Multicore examples cm7 side cannot be built as cm7 example has targets flexspi_nor_debug|release and cm4 has debug|release targets. CM7 is expecting M4 binary at ../<cm4project>/flexspi_nor_debug|release but binary is placed at debug|release folder.
[erpc_matrix_multiply_mu_rtos.zip](https://github.com/NXPmicro/mcux-sdk-examples/files/6847381/erpc_matrix_multiply_mu_rtos.zip) -> tak look into armgcc build_<target>.sh and CmakeList.txt for both cores.

I noticed that when i was trying to use standalone app bellow
[erpc_matrix_multiply_mu_rtos_cm4_erpc_matrix_multiply_mu_rtos_cm7.zip](https://github.com/NXPmicro/mcux-sdk-examples/files/6847393/erpc_matrix_multiply_mu_rtos_cm4_erpc_matrix_multiply_mu_rtos_cm7.zip)

Issue is at least in rpmsg and mu examples. Not sure if in others too.

**Comment by MichalPrincNXP** [comment]
Hello @Hadatko , thank you for reporting this behavior. This issue relates to standalone multicore examples, all is ok when building from the sdk package (please use this way until the fix for standalone rt1170 multicore apps is applied). Thank you.
Regards
Michal

**Comment by Hadatko** [comment]
Thank you for investigation of this issue.

**Comment by mcuxsusan** [comment]
Hi @Hadatko, do you have same issue for GitHub SDK delivery? If this issue only exists on standalone multicore example package built from mcuxpresso.nxp.com, I would like to close the issue here.

**Comment by Hadatko** [comment]
Hi @mcuxsusan SDK delivery from GITHUB i didn't try, but generated SDK package is ok. But the folder structure we are using is taken from example package.

Maybe the name of issue can be renamed to be more specific. But if you want to close it before fixing it it is up to you.

**Comment by mcuxsusan** [comment]
@Hadatko, thanks for your update. @MichalPrincNXP, could you please provide some detail about how the issue will be fixed and when it will be fixed?
I would like to close the issue after you have updated the information about the fix.

**Comment by MichalPrincNXP** [comment]
@mcuxsusan , this problem has been reported to and being solved by the imx conf tools team. Based on internal records it should be fixed in v11 EAR1. The rootcause are different target names on the cm7 and cm4 sides (specific for imxrt1170/1160).
