### ISSUE TITLE
rt1170-EVK Error 404 uSD Jumpers not found.

### ISSUE THREAD

**Issue by Hadatko** [nxp-mcuxpresso/mcux-sdk-examples#6]
Hi, i am trying wifi example (wifi-cli) and from example readme: 
![image](https://user-images.githubusercontent.com/13130700/126506608-9372d1af-1d71-4aa3-ac58-870f717fbf41.png)

On my board J11 looks like it is not jumper. J2 i didn't find so far, but i found J1 and J3.
![photo_2021-07-21_16-21-31](https://user-images.githubusercontent.com/13130700/126506989-8f5837f1-c62f-4fc1-87ad-143ca9258608.jpg)

`UPDATE`
J2 Found
![j2](https://user-images.githubusercontent.com/13130700/126507968-015fd26b-e68c-4fd8-ae93-4160072b4f1f.jpg)

`UPDATE`
BT spp example requires J11, J2 and J4
J4 is second ethernet port :/

**Comment by Hadatko** [comment]
Hi @mcuxsusan , do you know anybody who can check jumpers for wifi/ble examples?

**Comment by mcuxsusan** [comment]
@Lucien-Zhao, may you please help?

**Comment by Lucien-Zhao** [comment]
What is your confused？ I‘m not very clear.

**Comment by Hadatko** [comment]
Where are the jumpers mentioned in documentation?

**Comment by Hadatko** [comment]
With jumpers i was expecting something like this ![divide-jumpers-00.jpg](https://user-images.githubusercontent.com/13130700/126978963-12a76401-63fd-4ec1-87de-ea499bc8c90b.jpg)

**Comment by Hadatko** [comment]
I am closing this as i got right answer from other source.
I didn't realized that i am using different wifi module (in m.2 slot not uSD). So i was looking for jumpers on rt1170 instead of uSD module which i don't have.

My solution should be this:
![image](https://user-images.githubusercontent.com/13130700/127013837-408a7c6a-64e5-4722-b93b-a3a0c376b023.png)

**Comment by Lucien-Zhao** [comment]
Hi @Hadatko 
    I'm glad to hear that your problem has been solved.
    By the way, could you update the information about #7 ticket after trying my comment on your side?
