### ISSUE TITLE
RT1170-EVK - Bluetooth not working with AW-AM457MA-D module

### ISSUE THREAD

**Issue by mojo150** [nxp-mcuxpresso/mcux-sdk-examples#8]
Hi, I have problem with bluetooth example for RT1170-EVK dev board. To be specific it is "edgefast_bluetooth_examples/spp"
It is not woring, when trying to debug, I am getting error messages in serial console:
`[wifi_io] Error: Error in wlan_card_status()`
`[wifi_io] Error: Card timeout wlan_download_normal_fw:361`
`[wifi] Error: sd_wifi_init failed. status code -1`
`ASSERT ERROR " WM_SUCCESS == result ": file "/home/mojmir/Dokumenty/SDK/SDK_2_10_0_MIMXRT1170-EVK/middleware/wireless/ethermind/port/pal/mcux/bluetooth/controller/controller_wifi_nxp.c" Line "56" function name "controller_wifi_nxp_init" `

But I am afraid that this is caused by attempt to debug program, because the same error I am getting when debugging WiFi example (but it makes sense, as it is independent module). 
When I am running this example without debugging, just after power on of board, I get only fragment of error message and nothing else in console (WiFi example is running OK with the same module, but it uses different bus).

Have you been able to run this bluetooth example? Is there any way how to properly debug this?
I built it with armgcc.

**Comment by mcuxsusan** [comment]
@lylezhu2014, could you please help this issue?

**Comment by mcuxsusan** [comment]
Hello @mojo150, I navigated the example and found this is not available on GitHub yet. I checked your description and it seems you are encountering this issue with SDK package. For SDK package support, please raise the question to https://community.nxp.com/, we have another team covering support of SDK package.
